Repository AY2324S2-CS2103T-W10-1/tp, pull requests merged in 2024-04, with the labels that each got.

#206 Modify tests related to edit function to include new birthday field
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/realodex/testutil/EditPersonDescriptorBuilder.java
Labels: priority.Medium, severity.Medium

#211 Update UG to add `sort` and update command features
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Documentation

#214 Update Storage and Model Class uml diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation

#195 New field housing type
  src/main/java/seedu/realodex/logic/commands/AddCommand.java
  src/main/java/seedu/realodex/logic/commands/EditCommand.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/CliSyntax.java
  src/main/java/seedu/realodex/logic/parser/EditCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/logic/parser/Prefix.java
  src/main/java/seedu/realodex/model/person/HousingType.java
  src/main/java/seedu/realodex/model/person/Person.java
  src/main/java/seedu/realodex/model/util/SampleDataUtil.java
  src/main/java/seedu/realodex/storage/JsonAdaptedPerson.java
  src/main/java/seedu/realodex/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableRealodexTest/duplicatePersonRealodex.json
  src/test/data/JsonSerializableRealodexTest/typicalPersonsRealodex.json
  src/test/java/seedu/realodex/logic/LogicManagerTest.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/realodex/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ParserUtilTest.java
  src/test/java/seedu/realodex/model/person/HousingTypeTest.java
  src/test/java/seedu/realodex/model/person/PersonTest.java
  src/test/java/seedu/realodex/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/realodex/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/realodex/testutil/PersonBuilder.java
  src/test/java/seedu/realodex/testutil/PersonUtil.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#217 Fix the toString method in housingType to suit the JSON parsing
  src/main/java/seedu/realodex/model/person/HousingType.java
  src/test/java/seedu/realodex/model/person/HousingTypeTest.java
Labels: priority.High, type.Bug, severity.High

#223 V1.3 fix filter birthdays
  src/main/java/seedu/realodex/logic/commands/FilterCommand.java
  src/main/java/seedu/realodex/logic/parser/FilterCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/logic/parser/RealodexParser.java
  src/main/java/seedu/realodex/model/Model.java
  src/main/java/seedu/realodex/model/ModelManager.java
  src/main/java/seedu/realodex/model/person/Birthday.java
  src/main/java/seedu/realodex/model/person/predicates/BirthdayIsInMonthPredicate.java
  src/main/java/seedu/realodex/model/person/predicates/NameContainsKeyphrasePredicate.java
  src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java
  src/main/java/seedu/realodex/model/person/predicates/TagsMatchPredicate.java
  src/main/java/seedu/realodex/ui/PersonListPanel.java
  src/test/java/seedu/realodex/logic/commands/FilterCommandTest.java
  src/test/java/seedu/realodex/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
  src/test/java/seedu/realodex/model/person/predicates/BirthdayIsInMonthPredicateTest.java
Labels: priority.High

#220 V1.3 Filter by Housing Type Preference
  src/main/java/seedu/realodex/logic/commands/FilterCommand.java
  src/main/java/seedu/realodex/logic/parser/FilterCommandParser.java
  src/main/java/seedu/realodex/model/person/predicates/HousingTypeMatchPredicate.java
  src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java
  src/test/data/JsonSerializableRealodexTest/typicalPersonsRealodex.json
  src/test/java/seedu/realodex/logic/commands/FilterCommandTest.java
  src/test/java/seedu/realodex/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java
  src/test/java/seedu/realodex/model/person/PhoneTest.java
  src/test/java/seedu/realodex/model/person/TagTest.java
  src/test/java/seedu/realodex/model/person/predicate/HousingTypeMatchPredicateTest.java
  src/test/java/seedu/realodex/model/person/predicate/PredicateProducerTest.java
  src/test/java/seedu/realodex/model/remark/RemarkTest.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.High

#215 V1.3 feature flaw `EditCommandParser` should return stacked edit error messages, refactor `AddCommandParser`, add more tests
  docs/UserGuide.md
  src/main/java/seedu/realodex/logic/Messages.java
  src/main/java/seedu/realodex/logic/commands/AddCommand.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/realodex/logic/parser/EditCommandParser.java
  src/test/java/seedu/realodex/logic/commands/EditCommandTest.java
  src/test/java/seedu/realodex/logic/commands/SortCommandTest.java
  src/test/java/seedu/realodex/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement, severity.Medium, type.FeatureFlaw

#218 V1.3b update ug
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.Documentation

#227 V1.3b wrap text in personcard
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, severity.Medium, type.FeatureFlaw

#228 Add simple change to make duplicate prefix error clearer
  src/main/java/seedu/realodex/logic/Messages.java
Labels: priority.Medium, type.FeatureFlaw

#213 V1.3b update ug
  docs/UserGuide.md
  docs/duplicate_person_error.png
  docs/excessive_fields
  docs/missing_fields_error
  docs/parsing_errors
Labels: priority.High, type.Documentation

#226 V1.3 Update documentation for filter command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/filter/FilterClass.puml
  docs/diagrams/filter/FilterFeatureArchitecture.png
  docs/diagrams/filter/FilterFeatureArchitecture.puml
  docs/images/filter/filterByBirthday.png
  docs/images/filter/filterByHousingType.png
  docs/images/filter/filterByNameScreenshot.png
  docs/images/filter/filterByRemarkScreenshot.png
  docs/images/filter/filterByTagBuyerSeller.png
  docs/images/filter/filterByTagSeller.png
  docs/img_1.png
  src/test/java/seedu/realodex/model/person/predicates/HousingTypeMatchPredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/NameContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/PredicateProducerTest.java
  src/test/java/seedu/realodex/model/person/predicates/RemarkContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/TagsMatchPredicateTest.java
Labels: priority.High, type.Documentation

#237 Update the UG and finalise formatting
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/add-command/duplicate_person_error.png
  docs/images/add-command/excessive_fields_error.png
  docs/images/add-command/missing_fields_error.png
  docs/images/help/clear_help.png
  docs/images/help/delete_help.png
  docs/parsing_errors
  docs/parsing_errors.png
Labels: priority.High, severity.Medium, type.Documentation

#285 V1.4 Minor update docs for filter feature documentation
  docs/UserGuide.md
Labels: priority.High

#287 Update UG for expected Birthday errors, DG for Add diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/add/AddCommandSequenceDiagram.puml
  docs/diagrams/add/remark/ParserClass.puml
  docs/diagrams/add/remark/RemarkClass.puml
  docs/diagrams/add/tag/ParserClass.puml
  docs/team/4llysa.md
Labels: type.Documentation

#291 Update quick start section, `sort`
  docs/UserGuide.md
  docs/images/misc_features/clear.png
  docs/images/quick-start/cd.png
  docs/images/quick-start/java-version-macs.png
  docs/images/quick-start/java-version.png
  docs/images/quick-start/release.png
  docs/images/quick-start/running.png
  docs/images/quick-start/ui.png
  docs/images/sort/sort-day_showcase.png
Labels: type.Documentation

#296 Fix `FAMILY` check, fix `EMAIL` regex, add UG edits
  docs/UserGuide.md
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/EditCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/model/person/Address.java
  src/main/java/seedu/realodex/model/person/Email.java
  src/main/java/seedu/realodex/model/person/Family.java
  src/main/java/seedu/realodex/model/person/HousingType.java
  src/main/java/seedu/realodex/model/person/Income.java
  src/main/java/seedu/realodex/model/person/Name.java
  src/main/java/seedu/realodex/model/person/Phone.java
  src/test/java/seedu/realodex/model/person/EmailTest.java
  src/test/java/seedu/realodex/model/person/FamilyTest.java
Labels: priority.High, severity.High, type.Documentation

#306 Update sequence diagram for filter command
  docs/DeveloperGuide.md
  docs/diagrams/filter/FilterSequenceDiagram.puml
Labels: priority.High

#297 DG - Add enhancements, update NFRs, add line breaks
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassUpdated.puml
  docs/diagrams/add/AddCommandSequenceDiagram.puml
  docs/diagrams/sort/NewSortSequenceDiagram-Logic.puml
  docs/diagrams/sort/SortSequenceDiagram-Logic.puml
Labels: priority.High, type.Documentation

#311 V1.4 Add EP tests
  docs/diagrams/sort/SortSequenceDiagram-Logic.puml
  src/test/java/seedu/realodex/logic/commands/AddCommandTest.java
  src/test/java/seedu/realodex/logic/commands/CommandResultTest.java
  src/test/java/seedu/realodex/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/realodex/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/realodex/model/person/AddressTest.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
  src/test/java/seedu/realodex/model/person/EmailTest.java
  src/test/java/seedu/realodex/model/person/FamilyTest.java
  src/test/java/seedu/realodex/model/person/HousingTypeTest.java
  src/test/java/seedu/realodex/model/person/IncomeTest.java
  src/test/java/seedu/realodex/model/person/NameTest.java
  src/test/java/seedu/realodex/model/person/PhoneTest.java
  src/test/java/seedu/realodex/model/person/RemarkTest.java
  src/test/java/seedu/realodex/model/person/TagTest.java
  src/test/java/seedu/realodex/model/person/predicates/BirthdayIsInMonthPredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/HousingTypeMatchPredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/NameContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/PredicateProducerTest.java
  src/test/java/seedu/realodex/model/person/predicates/RemarkContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/person/predicates/TagsMatchPredicateTest.java
Labels: priority.Medium, severity.Low

#315 Update version number
  src/main/java/seedu/realodex/MainApp.java
Labels: priority.High
