Repository AY2324S2-CS2103T-W10-1/tp, pull requests merged in 2024-03, with the labels that each got.

#63 Update DG use cases according to new CLI constraint
  docs/DeveloperGuide.md
Labels: priority.High

#62 Update the UserGuide by editing and removing wrong information
  docs/UserGuide.md
Labels: type.Task

#64 Remove family size extension use case
  docs/DeveloperGuide.md
Labels: priority.High

#78 V1.2 Morph add command to take in income and family size.
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Family.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement, type.Task

#82 Add TeamWorkflow.md
  README.md
  docs/DeveloperGuide.md
  docs/TeamWorkflow.md
  docs/UserGuide.md
  docs/team/appleraincoat.md
  docs/team/jyztintan.md
Labels: priority.Low, type.Enhancement

#85 Update the User Guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium, type.Enhancement

#83 V1.2 help enhance help command
  copyright.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Family.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/realodex_icon.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.Enhancement, type.Task

#92 Add Edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Income.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/FamilyTest.java
  src/test/java/seedu/address/model/person/IncomeTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Enhancement

#95 V1.2 types add seller buyer status
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#112 V1.2 add remarks
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/remark/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#104 V1.2 Substring-Based 'Filter' Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeyphrasePredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeyphrasePredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#109 V1.2 refactor income and family, add all new tests for income and family fields
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Family.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/FamilyTest.java
  src/test/java/seedu/address/model/person/IncomeTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#118 Add 'Delete by Name' Functionality and Enhance Test Coverage
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommandExecutor.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#128 Update Tag tests
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  test.txt
Labels: priority.Medium, severity.Medium

#131 V1.2b enhance tests, add `Remark` and `DeleteCommand` related tests
  src/main/java/seedu/realodex/model/remark/Remark.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/realodex/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ParserUtilTest.java
  src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java
  src/test/java/seedu/realodex/model/person/NameTest.java
  src/test/java/seedu/realodex/model/person/PersonTest.java
  src/test/java/seedu/realodex/model/person/RemarkTest.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement

#132 Week 9 `ModelClassDiagram` UML update
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: severity.VeryLow, priority.Medium, type.Enhancement, type.Task

#138 Update BetterModelClassDiagram.puml and make other minor changes
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: severity.VeryLow, priority.Medium, type.Enhancement

#156 Modify clear command
  docs/UserGuide.md
  src/main/java/seedu/realodex/logic/commands/ClearCommand.java
Labels: priority.High, type.Task

#150 `AddCommand` parse names as name capitalized by default and raise specific error for missing `Prefix`, make `Prefix` tags case-insensitive, stack `ParserException` messages
  build.gradle
  docs/img.png
  src/main/java/seedu/realodex/logic/Messages.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/realodex/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/realodex/logic/parser/CliSyntax.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/logic/parser/ParserUtilResult.java
  src/main/java/seedu/realodex/logic/parser/Prefix.java
  src/main/java/seedu/realodex/model/person/Address.java
  src/main/java/seedu/realodex/model/person/Email.java
  src/main/java/seedu/realodex/model/person/Family.java
  src/main/java/seedu/realodex/model/person/Income.java
  src/main/java/seedu/realodex/model/person/Name.java
  src/main/java/seedu/realodex/model/person/Phone.java
  src/test/java/seedu/realodex/logic/LogicManagerTest.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/commands/EditCommandTest.java
  src/test/java/seedu/realodex/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/realodex/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/realodex/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ParserUtilTest.java
  src/test/java/seedu/realodex/model/person/PersonTest.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement, type.FeatureFlaw

#165 Update GUI colours and background
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: priority.Medium

#155 Delete name index provided
  src/main/java/seedu/realodex/logic/commands/DeleteCommand.java
  src/main/java/seedu/realodex/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/realodex/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Task, type.FeatureFlaw

#183 V1.3 Implement filter by remarks
  src/main/java/seedu/realodex/logic/commands/EditCommand.java
  src/main/java/seedu/realodex/logic/commands/FilterCommand.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/realodex/logic/parser/EditCommandParser.java
  src/main/java/seedu/realodex/logic/parser/FilterCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/logic/parser/PrefixChecker.java
  src/main/java/seedu/realodex/model/person/Person.java
  src/main/java/seedu/realodex/model/person/Remark.java
  src/main/java/seedu/realodex/model/person/predicates/NameContainsKeyphrasePredicate.java
  src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java
  src/main/java/seedu/realodex/model/person/predicates/RemarkContainsKeyphrasePredicate.java
  src/main/java/seedu/realodex/model/util/SampleDataUtil.java
  src/main/java/seedu/realodex/storage/JsonAdaptedPerson.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/commands/FilterCommandTest.java
  src/test/java/seedu/realodex/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ParserUtilTest.java
  src/test/java/seedu/realodex/logic/parser/PrefixCheckerTest.java
  src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java
  src/test/java/seedu/realodex/model/ModelManagerTest.java
  src/test/java/seedu/realodex/model/person/RemarkTest.java
  src/test/java/seedu/realodex/model/person/predicate/NameContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/person/predicate/PredicateProducerTest.java
  src/test/java/seedu/realodex/model/person/predicate/RemarkContainsKeyphrasePredicateTest.java
  src/test/java/seedu/realodex/model/remark/RemarkTest.java
  src/test/java/seedu/realodex/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/realodex/testutil/PersonBuilder.java
Labels: priority.High

#187 v1.3 Update DeveloperGuide with Sort by birthday features
  docs/DeveloperGuide.md
Labels: priority.High

#154 V1.3 add birthday field
  src/main/java/seedu/realodex/logic/commands/EditCommand.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/realodex/logic/parser/CliSyntax.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/model/person/Birthday.java
  src/main/java/seedu/realodex/model/person/Person.java
  src/main/java/seedu/realodex/model/util/SampleDataUtil.java
  src/main/java/seedu/realodex/storage/JsonAdaptedPerson.java
  src/main/java/seedu/realodex/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableRealodexTest/typicalPersonsRealodex.json
  src/test/java/seedu/realodex/logic/LogicManagerTest.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
  src/test/java/seedu/realodex/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/realodex/testutil/PersonBuilder.java
  src/test/java/seedu/realodex/testutil/PersonUtil.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#189 V1.3 update dg
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.Medium, severity.Medium, type.Task

#188 Refactor `Prefix` back to one constructor field, fix `Birthday` to prevent `NoElementException`
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/realodex/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/realodex/logic/parser/CliSyntax.java
  src/main/java/seedu/realodex/logic/parser/Prefix.java
  src/test/java/seedu/realodex/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/realodex/model/person/predicate/PredicateProducerTest.java
Labels: priority.Medium

#192 V1.3 fix `Birthday` and add tests
  src/main/java/seedu/realodex/logic/Messages.java
  src/main/java/seedu/realodex/logic/commands/AddCommand.java
  src/main/java/seedu/realodex/logic/parser/AddCommandParser.java
  src/main/java/seedu/realodex/logic/parser/ParserUtil.java
  src/main/java/seedu/realodex/model/person/Birthday.java
  src/main/java/seedu/realodex/model/person/Person.java
  src/main/java/seedu/realodex/model/util/SampleDataUtil.java
  src/main/java/seedu/realodex/storage/JsonAdaptedPerson.java
  src/main/java/seedu/realodex/storage/JsonSerializableRealodex.java
  src/test/data/JsonSerializableRealodexTest/duplicatePersonRealodex.json
  src/test/data/JsonSerializableRealodexTest/typicalPersonsRealodex.json
  src/test/java/seedu/realodex/logic/LogicManagerTest.java
  src/test/java/seedu/realodex/logic/commands/CommandTestUtil.java
  src/test/java/seedu/realodex/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/ParserUtilTest.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
  src/test/java/seedu/realodex/model/person/PersonTest.java
  src/test/java/seedu/realodex/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/realodex/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/realodex/testutil/TypicalPersons.java
Labels: priority.High, severity.High

#194 Update Error Colour to be more visible on the background
  src/main/resources/view/Extensions.css
Labels: priority.Low, severity.Low

#191 V1.3 Filter by Tags
  src/main/java/seedu/realodex/logic/Messages.java
  src/main/java/seedu/realodex/logic/commands/FilterCommand.java
  src/main/java/seedu/realodex/logic/parser/FilterCommandParser.java
  src/main/java/seedu/realodex/logic/parser/PrefixChecker.java
  src/main/java/seedu/realodex/model/person/predicates/NameContainsKeyphrasePredicate.java
  src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java
  src/main/java/seedu/realodex/model/person/predicates/TagsMatchPredicate.java
  src/test/java/seedu/realodex/logic/commands/FilterCommandTest.java
  src/test/java/seedu/realodex/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/realodex/logic/parser/PrefixCheckerTest.java
  src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java
  src/test/java/seedu/realodex/model/person/predicate/PredicateProducerTest.java
  src/test/java/seedu/realodex/model/person/predicate/TagsMatchPredicateTest.java
Labels: priority.High

#198 Fix the logic for checking valid dates and tests
  src/main/java/seedu/realodex/model/person/Birthday.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
Labels: type.Bug

#200 Building on the sort by birthday feature
  src/main/java/seedu/realodex/logic/commands/HelpCommand.java
  src/main/java/seedu/realodex/logic/commands/SortCommand.java
  src/main/java/seedu/realodex/logic/parser/RealodexParser.java
  src/main/java/seedu/realodex/model/ModelManager.java
  src/main/java/seedu/realodex/model/ReadOnlyRealodex.java
  src/main/java/seedu/realodex/model/Realodex.java
  src/main/java/seedu/realodex/model/person/Birthday.java
  src/main/java/seedu/realodex/model/person/UniquePersonList.java
  src/main/java/seedu/realodex/model/person/sorting/BirthdayComparator.java
  src/main/java/seedu/realodex/ui/HelpWindow.java
  src/main/java/seedu/realodex/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/realodex/logic/commands/HelpCommandTest.java
  src/test/java/seedu/realodex/logic/commands/SortCommandTest.java
  src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java
  src/test/java/seedu/realodex/model/RealodexTest.java
  src/test/java/seedu/realodex/model/person/BirthdayTest.java
  src/test/java/seedu/realodex/model/person/sorting/BirthdayComparatorTest.java
Labels: priority.High

#179 Refresh list delete command
  src/main/java/seedu/realodex/logic/commands/DeleteCommand.java
  src/test/java/seedu/realodex/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/realodex/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium, type.Task
